### ISSUE TITLE
Ensemble

### ISSUE THREAD

**Issue by martinwimpff** [Altaheri/EEG-ATCNet#12]
Hi @Altaheri,

thanks for making your code public.
As far as I understand the code, the sliding window procedure does not only introduce n_windows more function calls but also introduces n_windows more model paramteres.

[This for-loop](https://github.com/Altaheri/EEG-ATCNet/blob/12a4a53c3262a899b3e6b5856d5a9ef9eac6282b/models.py#L64) creates a new "AT-Block" (consisting of an attention block, a TCN and a Dense layer) per window. This would effectively make your ATCNet an Ensemble model where each window would have its own "AT-Block". Is this a wanted behaviour? As far as I understood the paper I thought that there is only one "AT-Block" that is shared between all windows.

**Comment by Altaheri** [comment]
Yes, that's right, the feature map generated from _Conv_block_ is divided into several windows and each window is enteded into separate "attention + TCN layers". The output from all windows is then averaged or concatenated and fed into a dense layer. The following figure may give a clearer description of the model
https://www.researchgate.net/profile/Hamdi-Altaheri/publication/370976919/figure/fig1/AS:11431281160813054@1684860317357/Components-of-the-D-ATCNet-architecture-The-temporal-spatial-channel-and-spectral_W640.jpg

**Comment by martinwimpff** [comment]
Thanks for the clarification!
It is an ensemble for both publications - right? In what sense does the second publication differ from the first one?

One other question about the data split:
For subject-specific you train one model per subject on 288 trials from session_T and test on the 288 trials from session_E?
For the LOSO-case you train one model per subject on 288*8*2 trials of the other 8 subjects and test on the 288*2 trials of the "target subject"?

**Comment by Altaheri** [comment]
The second paper ([D-ATCNet](http://dx.doi.org/10.1109/JIOT.2023.3281911)) differs from first paper ([ATCNet](http://dx.doi.org/10.1109/TII.2022.3197419)) by using multilevelattention at the kernel level using dynamic convolution and atthe features level using MSA and SE. In features level attention,we investigate the temporal, spectral, and spatial domains of theEEG signal. D-ATCNet also uses multi-head locality self-attention (MLSA) instead of multi-head self-attention,which helps learn attention representations for small datasets 

(PDF) Dynamic convolution with multilevel attention for EEG-based motor imagery decoding. Available from: https://www.researchgate.net/publication/370976919_Dynamic_convolution_with_multilevel_attention_for_EEG-based_motor_imagery_decoding [accessed Jul 05 2023].

**Comment by Altaheri** [comment]
That's right _"For subject-specific you train one model per subject on 288 trials from session_T and test on the 288 trials from session_E? 
For the LOSO-case you train one model per subject on 28882 trials of the other 8 subjects and test on the 288*2 trials of the "target subject"?"_
